### ISSUE TITLE
Feedback for “Quickstart with Supabase”

### ISSUE THREAD

**Issue by mschacker** [PlasmoHQ/docs#31]
I am building a Plasmo extension using Svelte and am trying to send data to Supabase. I created a .env.local file with the environment variables (PLASMO_PUBLIC_SUPABASE_URL, PLASMO_PUBLIC_SUPABASE_KEY). However, the env variables cannot be accessed from the background script or the popup (they are undefined). Any advice?

**Comment by louisgv** [comment]
> However, the env variables cannot be accessed from the background script or the popup

Can you paste some code snippet that you used for svelte and bgsw to access the env vars? -- I just tried and it works on my end with `process.env.PLASMO_PUBLIC_SUPABASE_URL`, so there might be some missing context.

Also, we should fix the doc to recommend the `.env.development` file instead of `.env.local` <- these should be deprecated IMO

**Comment by louisgv** [comment]
@mschacker I think GitHub doesn't support email attachment. Can you share it via a GitHub repo instead?

**Comment by mschacker** [comment]
Yes, I just sent you an invite...

**Comment by louisgv** [comment]
@mschacker I just tested your project with this `.env.development` file:

```
PLASMO_PUBLIC_SUPABASE_URL=XXXXXAAAABBBB
PLASMO_PUBLIC_SUPABASE_KEY=XXXXXAAAABBBB
```

And it worked:

![image](https://user-images.githubusercontent.com/6723574/213391794-4dea2903-c13b-4621-9321-3ba3d644912e.png)

Perhaps you didn't restart the dev server - it's required to apply the new env.

On another note - `background` in extension has a certain meaning - it's a service worker dedicated for async processes. You can have the `stores.ts` file in the background directory but you should avoid importing it into popup. 

If there are any shared logic, I'd move them to another directory (commonly `core`, `features`, `utils` or just a file at root directory) to share the common logic between [BGSW ](https://docs.plasmo.com/framework/background-service-worker) and [Popup/Extension pages](https://docs.plasmo.com/framework/ext-pages)
