### ISSUE TITLE
Feedback for “Itero TestBed”

### ISSUE THREAD

**Issue by jonathanyeung** [PlasmoHQ/docs#38]
It's not very clear from reading this section how to configure Github Integration.  I later found an option from within my Itero account page. 

I was actually expecting a way to upload my zip image from my own Github Action workflow.  Is this possible?  If not, could it be something that could be considered in the feature roadmap? My build has nuances that I'd rather control in my own repository instead of through the config on Itero's side.

Thanks in advance!

**Comment by ColdSauce** [comment]
Hey @jonathanyeung, thanks for reaching out! Sent you over an email.
