### ISSUE TITLE
missing command in quickstart guide with TailwindCSS 

### ISSUE THREAD

**Issue by Veer0x1** [PlasmoHQ/docs#53]
There is a missing command `npx tailwindcss init` to generate **tailwind.config.js** file

**Comment by louisgv** [comment]
Hahah that doc was created before we have the init with template feature. Can you fix the docs so that it says use this command to bootstrap the project:

```
pnpm create plasmo --with-tailwindcss
```

**Comment by Veer0x1** [comment]
You should also add the commands to initialise tailwind if someone has created project with just `pnpm create plasmo` command, can I fix this?

**Comment by louisgv** [comment]
You don't need to init tailwind separately since plasmo template already handled that :) - also I added that just now xD... MB, should have asked if you would like to fix it. In the future, please feel free to edit and send a PR instead of issue :D
