### ISSUE TITLE
Feedback for “Itero TestBed: Your Browser Extension Testing Solution”

### ISSUE THREAD

**Issue by xeroxcsn** [PlasmoHQ/docs#65]
when my team remove one extension on itero, all other extensions are also removed on the panel.

**Comment by louisgv** [comment]
@xeroxcsn I just tested it on prod and when removing one extension, it didn't remove the other. Can you please elaborate?

https://github.com/PlasmoHQ/docs/assets/6723574/68a90a87-130f-4568-9a0a-d0cd183782a5

**Comment by xeroxcsn** [comment]
My team has uploaded 4 versions of the same extension with different name and environment on itero, and when we remove one of them, all 4 versions were gone.

**Comment by louisgv** [comment]
@xeroxcsn can you send me your team's details to support@plasmo.com

If you can attach a video reproduction that'd be very helpful. When deleting an extension on itero, only that ID namespace get removed, the rest should have stayed intact (as seen in the video). There might be an edge case that I've overlooked 🤔

**Comment by xeroxcsn** [comment]
oh we just found it's a false alarm.

sorry for bordering your time, i am now closing this.
