### ISSUE TITLE
content-scripts-ui related issues

### ISSUE THREAD

**Issue by waflare** [PlasmoHQ/docs#72]
Current plasmo version: 0.57.2

Question：
Content-scripts-ui is injected into the html outside of the body, and I want to make sure that it's injected into the body.
![image](https://github.com/PlasmoHQ/docs/assets/73268185/3818eb17-f977-4456-91f7-b24c97c24175)

Don't see how to configure in the documentation
I was hoping you could help me

**Comment by louisgv** [comment]
Hey there - you can set the inline anchor and it will mount your  CSUI to the right place. By default it use overlay + document.documentElement
